<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="user01" failures="2" tests="2" name="BankingApp Test" time="130.185" errors="0" timestamp="2023-05-15T16:46:04 IST">
  <testcase classname="com.inetbanking.testCases.TC_LoginTest_001" name="LoginTest" time="32.228">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.testCases.TC_LoginTest_001.LoginTest(TC_LoginTest_001.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.inetbanking.testCases.TC_LoginTest_001" name="LoginTest" time="32.468">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:279)
at com.inetbanking.utilities.Reporting.onTestFailure(Reporting.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- BankingApp Test -->
